### ISSUE TITLE
Assertion failed: Too many element types registered. Out of (short) range.

### ISSUE THREAD

**Issue by smety** [nette-intellij/intellij-latte#39]
Hi, 
PHPStorm to 15 / 20 minutes return error in plugin:

`Assertion failed: Too many element types registered. Out of (short) range.`

Version: PhpStorm 2017.3.6.

**Comment by semisedlak** [comment]
Stack trace:

```
java.lang.Throwable: Too many element types registered. Out of (short) range. Most of element types (12153) were registered for 'Language: Latte': AUTO_CLOSED_BLOCK, EMPTY_MACRO_TAG, MACRO_CLASSIC, MACRO_CLOSE_TAG, MACRO_COMMENT, MACRO_CONTENT, MACRO_OPEN_TAG, NETTE_ATTR, NETTE_ATTR_VALUE, OUTER_HTML, LatteTokenType.T_HTML_TAG_ATTR_DQ, LatteTokenType.T_HTML_TAG_ATTR_EQUAL_SIGN, LatteTokenType.T_HTML_TAG_ATTR_SQ, LatteTokenType.T_HTML_TAG_NATTR...
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.psi.tree.IElementType.<init>(IElementType.java:112)
	at com.intellij.psi.tree.IElementType.<init>(IElementType.java:92)
	at com.intellij.psi.tree.ILazyParseableElementType.<init>(ILazyParseableElementType.java:43)
	at com.intellij.psi.tree.IFileElementType.<init>(IFileElementType.java:34)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.<init>(TemplateDataElementType.java:63)
	at com.jantvrdik.intellij.latte.psi.LatteFileViewProvider.createFile(LatteFileViewProvider.java:69)
	at com.intellij.psi.MultiplePsiFilesPerDocumentFileViewProvider.getPsiInner(MultiplePsiFilesPerDocumentFileViewProvider.java:84)
	at com.intellij.psi.AbstractFileViewProvider.getPsi(AbstractFileViewProvider.java:209)
	at com.intellij.psi.css.CssSupportLoader.isInFileThatSupportsEmbeddedCss(CssSupportLoader.java:29)
	at com.intellij.psi.css.CssPsiTreeChangeProcessor.acceptsEvent(CssPsiTreeChangeProcessor.java:34)
	at com.intellij.psi.impl.PsiTreeChangePreprocessorBase.treeChanged(PsiTreeChangePreprocessorBase.java:74)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:378)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChildrenChange(PsiManagerImpl.java:265)
	at com.intellij.psi.AbstractFileViewProvider.onContentReload(AbstractFileViewProvider.java:296)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.reloadPsiAfterTextChange(FileManagerImpl.java:596)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$MyFileDocumentManagerAdapter.lambda$fileWithNoDocumentChanged$0(PsiVFSListener.java:614)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1038)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$MyFileDocumentManagerAdapter.fileWithNoDocumentChanged(PsiVFSListener.java:608)
	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy27.fileWithNoDocumentChanged(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:141)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:121)
	at com.sun.proxy.$Proxy27.fileWithNoDocumentChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.contentsChanged(FileDocumentManagerImpl.java:616)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy23.contentsChanged(Unknown Source)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:65)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
	at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy21.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:890)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.c(RefreshSessionImpl.java:198)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:105)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:185)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.s(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by adawolfa** [comment]
Turning some unnecessary plugins solved the issue for me.

**Comment by mesour** [comment]
Old issue. If your problems persists on current version, please reopen issue
